"""JSON schema and parsing for candidate rules generated by the LLM.

Candidate rules are expected to be JSON objects with the following structure:
- context: predicate DAG
- exit: exit DAG
- action: side and size_multiplier
- horizon_bars: integer
- cadence: { kind: "fixed_step", step_seconds: integer }
- grounding: specification + assertion about its distribution
- price_spec_ref: 64-character spec_id string

This module validates the shape without enforcing all business logic (that
happens during finalize_rule).
"""

from __future__ import annotations

from typing import Any, Mapping


class CandidateValidationError(ValueError):
    """Raised when a candidate rule fails schema validation."""


def validate_candidate_shape(candidate: Any) -> None:
    """Validate that candidate has the required top-level structure.

    Raises CandidateValidationError if any required field is missing or
    has the wrong top-level type.
    """
    if not isinstance(candidate, Mapping):
        raise CandidateValidationError("candidate must be a mapping")

    required_keys = {
        "context",
        "exit",
        "action",
        "action_schema_version",
        "horizon_bars",
        "cadence",
        "grounding",
        "price_spec_ref",
    }

    missing = required_keys - set(candidate.keys())
    if missing:
        raise CandidateValidationError(f"missing required keys: {sorted(missing)}")

    # Top-level type checks
    if not isinstance(candidate["context"], Mapping):
        raise CandidateValidationError("context must be a mapping")
    if not isinstance(candidate["exit"], Mapping):
        raise CandidateValidationError("exit must be a mapping")
    if not isinstance(candidate["action"], Mapping):
        raise CandidateValidationError("action must be a mapping")
    if not isinstance(candidate["cadence"], Mapping):
        raise CandidateValidationError("cadence must be a mapping")
    if not isinstance(candidate["grounding"], Mapping):
        raise CandidateValidationError("grounding must be a mapping")

    # action_schema_version and horizon_bars
    if not isinstance(candidate["action_schema_version"], int):
        raise CandidateValidationError("action_schema_version must be an int")
    if not isinstance(candidate["horizon_bars"], int) or candidate["horizon_bars"] <= 0:
        raise CandidateValidationError("horizon_bars must be a positive int")

    # price_spec_ref
    if not isinstance(candidate["price_spec_ref"], str) or len(candidate["price_spec_ref"]) != 64:
        raise CandidateValidationError("price_spec_ref must be a 64-character string")
